from __future__ import annotations

from coherence.aegis.types import ScenarioPolicy

SOURCE_PHASE = "AEGIS-ADMISSION-CONTRACT-00"
ADMISSION_PACKET_NAME = "aegis_admission_packet.json"
FAILURE_RECEIPT_NAME = "aegis_failure_receipt.json"
NON_AUTHORITY_BOUNDARY_NAME = "aegis_admission_non_authority_boundary.json"

DECISIONS = {
    "admit",
    "admit_with_controls",
    "hold_for_human_review",
    "reject_fail_closed",
    "alarm_requires_elevated_review",
}

SCENARIO_POLICIES: dict[str, ScenarioPolicy] = {
    "valid_explicit_local_file_admit": {
        "decision": "admit",
        "reason_codes": ["explicit_local_file_scope_valid", "consent_present", "sonya_packetization_ready"],
        "source_scope_status": "configured_scope_valid",
        "consent_status": "consent_present",
        "grounding_status": "grounded_local_file_reference",
        "security_screen_status": "passed",
        "canonicalization_status": "canonicalized",
        "content_type": "local_file_reference",
        "request_envelope_ref": "fixture_request_envelope.json",
        "failure_receipt_ref": None,
        "human_review_required": False,
    },
    "valid_pasted_excerpt_admit_with_controls": {
        "decision": "admit_with_controls",
        "reason_codes": ["pasted_excerpt_scope_valid", "controls_required_for_excerpt", "sonya_packetization_ready"],
        "source_scope_status": "configured_scope_valid",
        "consent_status": "consent_present",
        "grounding_status": "grounded_pasted_excerpt_fixture",
        "security_screen_status": "passed_with_controls",
        "canonicalization_status": "canonicalized_with_controls",
        "content_type": "pasted_excerpt_fixture",
        "request_envelope_ref": "fixture_request_envelope_with_controls.json",
        "failure_receipt_ref": None,
        "human_review_required": True,
    },
    "missing_scope_hold_for_human_review": {
        "decision": "hold_for_human_review",
        "reason_codes": ["missing_configured_scope", "human_scope_review_required"],
        "source_scope_status": "missing_scope",
        "consent_status": "consent_present",
        "grounding_status": "grounding_incomplete",
        "security_screen_status": "not_evaluated_scope_missing",
        "canonicalization_status": "not_canonicalized",
        "content_type": "unknown",
        "request_envelope_ref": None,
        "failure_receipt_ref": FAILURE_RECEIPT_NAME,
        "human_review_required": True,
    },
    "missing_consent_reject_fail_closed": {
        "decision": "reject_fail_closed",
        "reason_codes": ["missing_consent", "fail_closed_no_request_envelope"],
        "source_scope_status": "configured_scope_present",
        "consent_status": "missing_consent",
        "grounding_status": "grounding_blocked",
        "security_screen_status": "blocked",
        "canonicalization_status": "not_canonicalized",
        "content_type": "local_file_reference",
        "request_envelope_ref": None,
        "failure_receipt_ref": FAILURE_RECEIPT_NAME,
        "human_review_required": True,
    },
    "hidden_file_reject_fail_closed": {
        "decision": "reject_fail_closed",
        "reason_codes": ["hidden_file_rejected", "fail_closed_no_request_envelope"],
        "source_scope_status": "out_of_scope_hidden_file",
        "consent_status": "consent_not_sufficient_for_hidden_file",
        "grounding_status": "grounding_blocked",
        "security_screen_status": "blocked_hidden_file",
        "canonicalization_status": "not_canonicalized",
        "content_type": "hidden_file_reference",
        "request_envelope_ref": None,
        "failure_receipt_ref": FAILURE_RECEIPT_NAME,
        "human_review_required": True,
    },
    "directory_scan_reject_fail_closed": {
        "decision": "reject_fail_closed",
        "reason_codes": ["directory_scan_rejected", "fail_closed_no_request_envelope"],
        "source_scope_status": "out_of_scope_directory_scan",
        "consent_status": "consent_not_sufficient_for_directory_scan",
        "grounding_status": "grounding_blocked",
        "security_screen_status": "blocked_directory_scan",
        "canonicalization_status": "not_canonicalized",
        "content_type": "directory_reference",
        "request_envelope_ref": None,
        "failure_receipt_ref": FAILURE_RECEIPT_NAME,
        "human_review_required": True,
    },
    "connector_without_scope_reject_fail_closed": {
        "decision": "reject_fail_closed",
        "reason_codes": ["connector_without_scope", "fail_closed_no_request_envelope"],
        "source_scope_status": "connector_scope_missing",
        "consent_status": "connector_consent_missing",
        "grounding_status": "grounding_blocked",
        "security_screen_status": "blocked_connector_without_scope",
        "canonicalization_status": "not_canonicalized",
        "content_type": "connector_reference",
        "request_envelope_ref": None,
        "failure_receipt_ref": FAILURE_RECEIPT_NAME,
        "human_review_required": True,
    },
    "model_candidate_without_sonya_reject_fail_closed": {
        "decision": "reject_fail_closed",
        "reason_codes": ["model_candidate_without_sonya_packetization", "fail_closed_no_request_envelope"],
        "source_scope_status": "configured_scope_present",
        "consent_status": "consent_present",
        "grounding_status": "sonya_packetization_missing",
        "security_screen_status": "blocked_model_candidate_without_sonya",
        "canonicalization_status": "not_canonicalized",
        "content_type": "model_candidate_output",
        "request_envelope_ref": None,
        "failure_receipt_ref": FAILURE_RECEIPT_NAME,
        "human_review_required": True,
    },
    "source_instruction_quarantine_hold": {
        "decision": "hold_for_human_review",
        "reason_codes": ["source_instruction_quarantine", "human_security_review_required"],
        "source_scope_status": "configured_scope_present",
        "consent_status": "consent_present",
        "grounding_status": "grounded_with_quarantine",
        "security_screen_status": "quarantined_source_instruction",
        "canonicalization_status": "held_before_canonical_request",
        "content_type": "local_file_reference",
        "request_envelope_ref": None,
        "failure_receipt_ref": FAILURE_RECEIPT_NAME,
        "human_review_required": True,
    },
    "side_effecting_action_alarm": {
        "decision": "alarm_requires_elevated_review",
        "reason_codes": ["side_effecting_action_requested", "elevated_review_required", "fail_closed_no_request_envelope"],
        "source_scope_status": "action_out_of_admission_scope",
        "consent_status": "action_consent_not_established",
        "grounding_status": "grounding_blocked",
        "security_screen_status": "alarm_side_effecting_action",
        "canonicalization_status": "not_canonicalized",
        "content_type": "side_effecting_action_request",
        "request_envelope_ref": None,
        "failure_receipt_ref": FAILURE_RECEIPT_NAME,
        "human_review_required": True,
    },
}

NON_AUTHORITY_BOUNDARY = {
    "aegis_admission_is_not_truth_certification": True,
    "aegis_admission_is_not_memory_write_authorization": True,
    "aegis_admission_is_not_deployment_authority": True,
    "aegis_admission_is_not_compliance_certification": True,
    "aegis_admission_is_not_legal_advice": True,
    "aegis_admission_is_not_audit_pass": True,
    "aegis_admission_is_not_attestation_success": True,
    "aegis_admission_is_not_product_release": True,
    "aegis_admission_is_not_product_readiness": True,
    "aegis_admission_is_not_final_answer_authority": True,
    "aegis_admission_is_not_accepted_evidence_authority": True,
    "aegis_admission_does_not_write_memory": True,
    "aegis_admission_does_not_admit_atlas_memory": True,
    "aegis_admission_does_not_export_traces": True,
    "aegis_admission_does_not_federate_pmr": True,
    "human_review_required": True,
}

FALSE_ADMISSION_FLAGS = {
    "provider_runtime_performed": False,
    "network_call_performed": False,
    "memory_write_performed": False,
    "atlas_memory_admission_performed": False,
    "trace_export_performed": False,
    "pmr_federation_performed": False,
    "product_readiness_claimed": False,
    "product_release_performed": False,
    "compliance_certification_emitted": False,
    "legal_advice_emitted": False,
    "audit_pass_claimed": False,
    "attestation_success_claimed": False,
    "truth_certification_emitted": False,
    "final_answer_authority_granted": False,
    "accepted_evidence_authority_granted": False,
}

BLOCKED_CLAIMS = [
    "AEGIS admission certifies truth",
    "AEGIS admission authorizes memory write",
    "AEGIS admission authorizes deployment",
    "AEGIS admission certifies compliance",
    "AEGIS admission provides legal advice",
    "AEGIS admission passes audit",
    "AEGIS admission releases product",
    "AEGIS admission proves product readiness",
    "AEGIS admission grants final-answer authority",
    "AEGIS admission grants accepted-evidence authority",
    "failed admission creates RequestEnvelope",
    "AEGIS is the whole Triadic Brain",
    "AEGIS replaces Sophia",
    "AEGIS replaces Sonya",
    "AEGIS is the Publisher",
]

ALLOWED_CLAIM = (
    "AEGIS-ADMISSION-CONTRACT-00 implements a local deterministic AEGIS admission contract that emits admission packets and failure receipts for configured AI work events, deciding whether an event is admitted, admitted with controls, held for human review, rejected fail-closed, or escalated to alarm, while preserving that AEGIS decides admissibility rather than truth and does not perform provider calls, network calls, memory writes, Atlas admission, trace export, PMR federation, product readiness, product release, compliance certification, legal advice, audit pass, attestation success, truth certification, final-answer authority, or accepted-evidence authority."
)

AEGIS_SOURCE_SCOPE_CONSENT_PHASE = "AEGIS-SOURCE-SCOPE-CONSENT-00"
SOURCE_SCOPE_PACKET_NAME = "aegis_source_scope_packet.json"
CONSENT_PACKET_NAME = "aegis_consent_packet.json"
SOURCE_SCOPE_CONSENT_BOUNDARY_NAME = "aegis_source_scope_consent_non_authority_boundary.json"

SOURCE_SCOPE_FALSE_FLAGS = {
    "hidden_file_read_performed": False,
    "directory_scan_performed": False,
    "connector_pull_performed": False,
    "provider_runtime_performed": False,
    "network_call_performed": False,
    "memory_write_performed": False,
    "atlas_memory_admission_performed": False,
    "trace_export_performed": False,
    "pmr_federation_performed": False,
    "product_readiness_claimed": False,
    "product_release_performed": False,
    "compliance_certification_emitted": False,
    "legal_advice_emitted": False,
    "audit_pass_claimed": False,
    "truth_certification_emitted": False,
    "final_answer_authority_granted": False,
    "accepted_evidence_authority_granted": False,
}

CONSENT_FALSE_FLAGS = {
    "consent_write_performed": False,
    "provider_runtime_performed": False,
    "network_call_performed": False,
    "memory_write_performed": False,
    "atlas_memory_admission_performed": False,
    "trace_export_performed": False,
    "pmr_federation_performed": False,
    "product_readiness_claimed": False,
    "product_release_performed": False,
    "compliance_certification_emitted": False,
    "legal_advice_emitted": False,
    "audit_pass_claimed": False,
    "truth_certification_emitted": False,
    "final_answer_authority_granted": False,
    "accepted_evidence_authority_granted": False,
}

SOURCE_SCOPE_NON_AUTHORITY_BOUNDARY = {
    "source_scope_check_is_not_truth_certification": True,
    "source_scope_check_is_not_memory_write_authorization": True,
    "source_scope_check_is_not_deployment_authority": True,
    "source_scope_check_is_not_compliance_certification": True,
    "source_scope_check_is_not_legal_advice": True,
    "source_scope_check_is_not_audit_pass": True,
    "source_scope_check_is_not_product_release": True,
    "source_scope_check_is_not_product_readiness": True,
    "source_scope_check_is_not_final_answer_authority": True,
    "source_scope_check_is_not_accepted_evidence_authority": True,
    "source_scope_check_does_not_write_memory": True,
    "source_scope_check_does_not_admit_atlas_memory": True,
    "source_scope_check_does_not_export_traces": True,
    "source_scope_check_does_not_federate_pmr": True,
    "human_review_required": True,
}

CONSENT_NON_AUTHORITY_BOUNDARY = {
    "consent_check_is_not_truth_certification": True,
    "consent_check_is_not_memory_write_authorization": True,
    "consent_check_is_not_deployment_authority": True,
    "consent_check_is_not_compliance_certification": True,
    "consent_check_is_not_legal_advice": True,
    "consent_check_is_not_audit_pass": True,
    "consent_check_is_not_product_release": True,
    "consent_check_is_not_product_readiness": True,
    "consent_check_is_not_final_answer_authority": True,
    "consent_check_is_not_accepted_evidence_authority": True,
    "consent_check_does_not_write_memory": True,
    "consent_check_does_not_admit_atlas_memory": True,
    "consent_check_does_not_export_traces": True,
    "consent_check_does_not_federate_pmr": True,
    "human_review_required": True,
}

SOURCE_SCOPE_CONSENT_NON_AUTHORITY_BOUNDARY = {
    **SOURCE_SCOPE_NON_AUTHORITY_BOUNDARY,
    **CONSENT_NON_AUTHORITY_BOUNDARY,
}

SOURCE_SCOPE_CONSENT_BLOCKED_CLAIMS = [
    "source scope check certifies truth",
    "source scope check authorizes memory write",
    "source scope check authorizes deployment",
    "source scope check certifies compliance",
    "source scope check provides legal advice",
    "source scope check passes audit",
    "source scope check releases product",
    "source scope check proves product readiness",
    "source scope check grants final-answer authority",
    "source scope check grants accepted-evidence authority",
    "consent check certifies truth",
    "consent check authorizes memory write",
    "consent check authorizes deployment",
    "consent check certifies compliance",
    "consent check provides legal advice",
    "consent check passes audit",
    "consent check releases product",
    "consent check proves product readiness",
    "consent check grants final-answer authority",
    "consent check grants accepted-evidence authority",
    "hidden file is allowed by default",
    "directory scan is allowed by default",
    "connector pull is allowed without explicit scope",
    "missing consent can proceed",
    "failed scope check creates RequestEnvelope",
    "failed consent check creates RequestEnvelope",
]

SOURCE_SCOPE_CONSENT_ALLOWED_CLAIM = (
    "AEGIS-SOURCE-SCOPE-CONSENT-00 implements local deterministic AEGIS source-scope and consent checks for configured AI work events, evaluating explicit local file selection, pasted excerpts, missing scope, hidden files, directory scans, connector scope, source-instruction quarantine, valid consent, missing consent, mismatched consent, revoked consent, expired consent, and human-review consent states, while preserving that AEGIS checks admissibility rather than truth and do not perform hidden-file reads, directory scans, connector pulls, provider calls, network calls, memory writes, Atlas admission, trace export, PMR federation, product readiness, product release, compliance certification, legal advice, audit pass, truth certification, final-answer authority, or accepted-evidence authority."
)

AEGIS_GROUNDING_BINDING_PHASE = "AEGIS-GROUNDING-BINDING-00"
GROUNDING_BINDING_PACKET_NAME = "aegis_grounding_binding_packet.json"
GROUNDING_FAILURE_RECEIPT_NAME = "aegis_grounding_failure_receipt.json"
GROUNDING_BINDING_BOUNDARY_NAME = "aegis_grounding_binding_non_authority_boundary.json"

GROUNDING_BINDING_FALSE_FLAGS = {
    "source_truth_certified": False,
    "compliance_certification_emitted": False,
    "legal_advice_emitted": False,
    "audit_pass_claimed": False,
    "truth_certification_emitted": False,
    "memory_write_performed": False,
    "atlas_memory_admission_performed": False,
    "trace_export_performed": False,
    "pmr_federation_performed": False,
    "provider_runtime_performed": False,
    "network_call_performed": False,
    "hidden_file_read_performed": False,
    "directory_scan_performed": False,
    "connector_pull_performed": False,
    "product_readiness_claimed": False,
    "product_release_performed": False,
    "final_answer_authority_granted": False,
    "accepted_evidence_authority_granted": False,
}

GROUNDING_BINDING_NON_AUTHORITY_BOUNDARY = {
    "grounding_binding_is_not_truth_certification": True,
    "grounding_binding_is_not_source_truth_certification": True,
    "grounding_binding_is_not_memory_write_authorization": True,
    "grounding_binding_is_not_deployment_authority": True,
    "grounding_binding_is_not_compliance_certification": True,
    "grounding_binding_is_not_legal_advice": True,
    "grounding_binding_is_not_audit_pass": True,
    "grounding_binding_is_not_attestation_success": True,
    "grounding_binding_is_not_product_release": True,
    "grounding_binding_is_not_product_readiness": True,
    "grounding_binding_is_not_final_answer_authority": True,
    "grounding_binding_is_not_accepted_evidence_authority": True,
    "grounding_binding_does_not_write_memory": True,
    "grounding_binding_does_not_admit_atlas_memory": True,
    "grounding_binding_does_not_export_traces": True,
    "grounding_binding_does_not_federate_pmr": True,
    "human_review_required": True,
}

GROUNDING_BINDING_BLOCKED_CLAIMS = [
    "grounding binding certifies truth",
    "grounding binding certifies source truth",
    "grounding binding authorizes memory write",
    "grounding binding authorizes deployment",
    "grounding binding certifies compliance",
    "grounding binding provides legal advice",
    "grounding binding passes audit",
    "grounding binding releases product",
    "grounding binding proves product readiness",
    "grounding binding grants final-answer authority",
    "grounding binding grants accepted-evidence authority",
    "failed grounding creates RequestEnvelope",
    "hash binding proves content truth",
    "evidence ref certifies compliance",
    "receipt ref certifies truth",
]

GROUNDING_BINDING_ALLOWED_CLAIM = (
    "AEGIS-GROUNDING-BINDING-00 implements local deterministic AEGIS grounding-binding artifacts that bind admitted source-scope and consent packets to canonical source references, content hashes, evidence references, and receipt links before downstream model-candidate, report-generation, evidence-map, or control-package use, while preserving that grounding binding checks admissibility linkage rather than truth and does not read hidden files, scan directories, pull connectors, call providers, perform network calls, write memory, admit Atlas memory, export traces, federate PMR, certify compliance, provide legal advice, pass audits, claim product readiness, release product, certify truth, grant final-answer authority, or grant accepted-evidence authority."
)

AEGIS_INSTRUCTION_QUARANTINE_PHASE = "AEGIS-INSTRUCTION-QUARANTINE-00"
INSTRUCTION_QUARANTINE_PACKET_NAME = "aegis_instruction_quarantine_packet.json"
INSTRUCTION_QUARANTINE_RECEIPT_NAME = "aegis_instruction_quarantine_receipt.json"
INSTRUCTION_QUARANTINE_BOUNDARY_NAME = "aegis_instruction_quarantine_non_authority_boundary.json"

INSTRUCTION_QUARANTINE_FALSE_FLAGS = {
    "source_content_executed": False,
    "instruction_executed": False,
    "hidden_file_read_performed": False,
    "directory_scan_performed": False,
    "connector_pull_performed": False,
    "provider_runtime_performed": False,
    "network_call_performed": False,
    "memory_write_performed": False,
    "atlas_memory_admission_performed": False,
    "trace_export_performed": False,
    "pmr_federation_performed": False,
    "compliance_certification_emitted": False,
    "legal_advice_emitted": False,
    "audit_pass_claimed": False,
    "truth_certification_emitted": False,
    "product_readiness_claimed": False,
    "product_release_performed": False,
    "final_answer_authority_granted": False,
    "accepted_evidence_authority_granted": False,
}

INSTRUCTION_QUARANTINE_NON_AUTHORITY_BOUNDARY = {
    "instruction_quarantine_is_not_truth_certification": True,
    "instruction_quarantine_is_not_source_truth_certification": True,
    "instruction_quarantine_is_not_memory_write_authorization": True,
    "instruction_quarantine_is_not_deployment_authority": True,
    "instruction_quarantine_is_not_compliance_certification": True,
    "instruction_quarantine_is_not_legal_advice": True,
    "instruction_quarantine_is_not_audit_pass": True,
    "instruction_quarantine_is_not_attestation_success": True,
    "instruction_quarantine_is_not_product_release": True,
    "instruction_quarantine_is_not_product_readiness": True,
    "instruction_quarantine_is_not_final_answer_authority": True,
    "instruction_quarantine_is_not_accepted_evidence_authority": True,
    "instruction_quarantine_does_not_execute_source_instructions": True,
    "instruction_quarantine_does_not_write_memory": True,
    "instruction_quarantine_does_not_admit_atlas_memory": True,
    "instruction_quarantine_does_not_export_traces": True,
    "instruction_quarantine_does_not_federate_pmr": True,
    "human_review_required": True,
}

INSTRUCTION_QUARANTINE_BLOCKED_CLAIMS = [
    "instruction quarantine certifies truth",
    "instruction quarantine certifies source truth",
    "instruction quarantine authorizes memory write",
    "instruction quarantine authorizes deployment",
    "instruction quarantine certifies compliance",
    "instruction quarantine provides legal advice",
    "instruction quarantine passes audit",
    "instruction quarantine releases product",
    "instruction quarantine proves product readiness",
    "instruction quarantine grants final-answer authority",
    "instruction quarantine grants accepted-evidence authority",
    "quarantined instruction executed",
    "source instruction controls downstream model",
    "source instruction controls report generation",
    "source instruction controls evidence map",
    "source instruction controls control package",
    "safe excerpt means truth certified",
    "quarantine receipt certifies compliance",
]

INSTRUCTION_QUARANTINE_ALLOWED_CLAIM = (
    "AEGIS-INSTRUCTION-QUARANTINE-00 implements local deterministic AEGIS instruction-quarantine artifacts that separate source content from source-borne instructions, preserve safe excerpt metadata, quarantine prompt-injection and instruction-like content for human review or fail-closed rejection, and prevent quarantined instructions from influencing downstream model-candidate, report-generation, evidence-map, or control-package use, while preserving that instruction quarantine checks admissibility and safety boundaries rather than truth and does not execute instructions, read hidden files, scan directories, pull connectors, call providers, perform network calls, write memory, admit Atlas memory, export traces, federate PMR, certify compliance, provide legal advice, pass audits, claim product readiness, release product, certify truth, grant final-answer authority, or grant accepted-evidence authority."
)

AEGIS_MODEL_CANDIDATE_GATE_PHASE = "AEGIS-MODEL-CANDIDATE-GATE-00"
MODEL_CANDIDATE_GATE_PACKET_NAME = "aegis_model_candidate_gate_packet.json"
MODEL_CANDIDATE_GATE_FAILURE_RECEIPT_NAME = "aegis_model_candidate_gate_failure_receipt.json"
MODEL_CANDIDATE_GATE_BOUNDARY_NAME = "aegis_model_candidate_gate_non_authority_boundary.json"

MODEL_CANDIDATE_GATE_FALSE_FLAGS = {
    "model_candidate_created": False,
    "provider_runtime_allowed": False,
    "provider_runtime_performed": False,
    "network_call_performed": False,
    "model_output_generated": False,
    "source_content_executed": False,
    "instruction_executed": False,
    "hidden_file_read_performed": False,
    "directory_scan_performed": False,
    "connector_pull_performed": False,
    "memory_write_performed": False,
    "atlas_memory_admission_performed": False,
    "trace_export_performed": False,
    "pmr_federation_performed": False,
    "compliance_certification_emitted": False,
    "legal_advice_emitted": False,
    "audit_pass_claimed": False,
    "truth_certification_emitted": False,
    "product_readiness_claimed": False,
    "product_release_performed": False,
    "final_answer_authority_granted": False,
    "accepted_evidence_authority_granted": False,
}

MODEL_CANDIDATE_GATE_NON_AUTHORITY_BOUNDARY = {
    "model_candidate_gate_is_not_truth_certification": True,
    "model_candidate_gate_is_not_source_truth_certification": True,
    "model_candidate_gate_is_not_memory_write_authorization": True,
    "model_candidate_gate_is_not_deployment_authority": True,
    "model_candidate_gate_is_not_compliance_certification": True,
    "model_candidate_gate_is_not_legal_advice": True,
    "model_candidate_gate_is_not_audit_pass": True,
    "model_candidate_gate_is_not_attestation_success": True,
    "model_candidate_gate_is_not_product_release": True,
    "model_candidate_gate_is_not_product_readiness": True,
    "model_candidate_gate_is_not_final_answer_authority": True,
    "model_candidate_gate_is_not_accepted_evidence_authority": True,
    "model_candidate_gate_does_not_call_provider": True,
    "model_candidate_gate_does_not_generate_model_output": True,
    "model_candidate_gate_does_not_execute_source_instructions": True,
    "model_candidate_gate_does_not_write_memory": True,
    "model_candidate_gate_does_not_admit_atlas_memory": True,
    "model_candidate_gate_does_not_export_traces": True,
    "model_candidate_gate_does_not_federate_pmr": True,
    "human_review_required": True,
}

MODEL_CANDIDATE_GATE_BLOCKED_CLAIMS = [
    "model candidate gate certifies truth",
    "model candidate gate certifies source truth",
    "model candidate gate authorizes memory write",
    "model candidate gate authorizes deployment",
    "model candidate gate certifies compliance",
    "model candidate gate provides legal advice",
    "model candidate gate passes audit",
    "model candidate gate releases product",
    "model candidate gate proves product readiness",
    "model candidate gate grants final-answer authority",
    "model candidate gate grants accepted-evidence authority",
    "model candidate gate calls provider",
    "model candidate gate generates model output",
    "allowed candidate means final answer",
    "allowed candidate means accepted evidence",
    "candidate_allowed means truth certified",
    "candidate_allowed_with_controls means audit passed",
    "failed model-candidate gate creates model output",
    "quarantined source can form model candidate without review",
    "rejected source can form model candidate",
    "alarmed source can form model candidate",
    "missing consent can form model candidate",
    "unbound grounding can form model candidate",
]

MODEL_CANDIDATE_GATE_ALLOWED_CLAIM = (
    "AEGIS-MODEL-CANDIDATE-GATE-00 implements local deterministic AEGIS model-candidate gate artifacts that evaluate whether compatible admission, source-scope, consent, grounding, and instruction-quarantine packets permit a downstream model candidate to be formed, while preserving that the prototype does not create model candidates, call providers, perform network calls, generate model output, execute source instructions, read hidden files, scan directories, pull connectors, write memory, admit Atlas memory, export traces, federate PMR, certify compliance, provide legal advice, pass audits, claim product readiness, release product, certify truth, grant final-answer authority, or grant accepted-evidence authority."
)


AEGIS_ACTION_FIREWALL_PHASE = "AEGIS-ACTION-FIREWALL-00"
ACTION_FIREWALL_PACKET_NAME = "aegis_action_firewall_packet.json"
ACTION_FIREWALL_FAILURE_RECEIPT_NAME = "aegis_action_firewall_failure_receipt.json"
ACTION_FIREWALL_BOUNDARY_NAME = "aegis_action_firewall_non_authority_boundary.json"

ACTION_FIREWALL_FALSE_FLAGS = {
    "action_performed": False,
    "tool_execution_allowed": False,
    "tool_execution_performed": False,
    "file_write_allowed": False,
    "file_write_performed": False,
    "file_delete_allowed": False,
    "file_delete_performed": False,
    "connector_pull_allowed": False,
    "connector_pull_performed": False,
    "connector_push_allowed": False,
    "connector_push_performed": False,
    "provider_runtime_allowed": False,
    "provider_runtime_performed": False,
    "network_call_allowed": False,
    "network_call_performed": False,
    "memory_write_allowed": False,
    "memory_write_performed": False,
    "atlas_memory_admission_allowed": False,
    "atlas_memory_admission_performed": False,
    "trace_export_allowed": False,
    "trace_export_performed": False,
    "pmr_federation_allowed": False,
    "pmr_federation_performed": False,
    "package_install_allowed": False,
    "package_install_performed": False,
    "package_activation_allowed": False,
    "package_activation_performed": False,
    "package_execution_allowed": False,
    "package_execution_performed": False,
    "payment_processing_allowed": False,
    "payment_processing_performed": False,
    "subscription_billing_allowed": False,
    "subscription_billing_performed": False,
    "marketplace_download_allowed": False,
    "marketplace_download_performed": False,
    "final_answer_emit_allowed": False,
    "final_answer_authority_granted": False,
    "accepted_evidence_mark_allowed": False,
    "accepted_evidence_authority_granted": False,
    "compliance_certification_emitted": False,
    "legal_advice_emitted": False,
    "audit_pass_claimed": False,
    "truth_certification_emitted": False,
    "product_readiness_claimed": False,
    "product_release_performed": False,
}

ACTION_FIREWALL_NON_AUTHORITY_BOUNDARY = {
    "action_firewall_is_not_truth_certification": True,
    "action_firewall_is_not_source_truth_certification": True,
    "action_firewall_is_not_memory_write_authorization": True,
    "action_firewall_is_not_deployment_authority": True,
    "action_firewall_is_not_compliance_certification": True,
    "action_firewall_is_not_legal_advice": True,
    "action_firewall_is_not_audit_pass": True,
    "action_firewall_is_not_attestation_success": True,
    "action_firewall_is_not_product_release": True,
    "action_firewall_is_not_product_readiness": True,
    "action_firewall_is_not_final_answer_authority": True,
    "action_firewall_is_not_accepted_evidence_authority": True,
    "action_firewall_does_not_execute_tools": True,
    "action_firewall_does_not_perform_actions": True,
    "action_firewall_does_not_call_provider": True,
    "action_firewall_does_not_call_network": True,
    "action_firewall_does_not_write_files": True,
    "action_firewall_does_not_delete_files": True,
    "action_firewall_does_not_pull_connectors": True,
    "action_firewall_does_not_push_connectors": True,
    "action_firewall_does_not_write_memory": True,
    "action_firewall_does_not_admit_atlas_memory": True,
    "action_firewall_does_not_export_traces": True,
    "action_firewall_does_not_federate_pmr": True,
    "human_review_required": True,
}

ACTION_FIREWALL_BLOCKED_CLAIMS = [
    "action firewall certifies truth",
    "action firewall authorizes memory write",
    "action firewall authorizes deployment",
    "action firewall certifies compliance",
    "action firewall provides legal advice",
    "action firewall passes audit",
    "action firewall releases product",
    "action firewall proves product readiness",
    "action firewall grants final-answer authority",
    "action firewall grants accepted-evidence authority",
    "action firewall executes tools",
    "action firewall performs actions",
    "action firewall writes files",
    "action firewall deletes files",
    "action firewall pulls connector data",
    "action firewall pushes connector data",
    "action firewall calls provider",
    "action firewall calls network",
    "action firewall writes memory",
    "action firewall admits Atlas memory",
    "action firewall exports traces",
    "action firewall federates PMR",
    "action firewall installs packages",
    "action firewall activates packages",
    "action firewall executes packages",
    "action firewall processes payment",
    "action firewall bills subscription",
    "action firewall downloads marketplace package",
    "model candidate eligibility authorizes action",
    "model_candidate_allowed means action allowed",
    "preview allowed means action performed",
    "operator authorization inferred from model output",
    "missing operator authorization can proceed",
]

ACTION_FIREWALL_ALLOWED_CLAIM = (
    "AEGIS-ACTION-FIREWALL-00 implements local deterministic AEGIS action-firewall artifacts that evaluate whether a proposed side-effecting action is eligible after model-candidate gating and explicit operator authorization, while preserving that the prototype does not execute tools, perform actions, write files, delete files, pull or push connectors, call providers, perform network calls, write memory, admit Atlas memory, export traces, federate PMR, install packages, activate packages, execute packages, process payments, bill subscriptions, download marketplace packages, certify compliance, provide legal advice, pass audits, claim product readiness, release product, certify truth, emit final answers, grant final-answer authority, or grant accepted-evidence authority."
)

AEGIS_RECEIPT_CHAIN_EXPORT_PHASE = "AEGIS-RECEIPT-CHAIN-EXPORT-00"
RECEIPT_CHAIN_EXPORT_MANIFEST_NAME = "aegis_receipt_chain_export_manifest.json"
RECEIPT_CHAIN_EXPORT_FAILURE_RECEIPT_NAME = "aegis_receipt_chain_export_failure_receipt.json"
RECEIPT_CHAIN_EXPORT_BOUNDARY_NAME = "aegis_receipt_chain_export_non_authority_boundary.json"

RECEIPT_CHAIN_EXPORT_FALSE_FLAGS = {
    "external_export_performed": False,
    "provider_runtime_performed": False,
    "network_call_performed": False,
    "tool_execution_performed": False,
    "file_write_performed": False,
    "connector_pull_performed": False,
    "connector_push_performed": False,
    "memory_write_performed": False,
    "atlas_memory_admission_performed": False,
    "trace_export_performed": False,
    "pmr_federation_performed": False,
    "package_install_performed": False,
    "package_activation_performed": False,
    "package_execution_performed": False,
    "payment_processing_performed": False,
    "subscription_billing_performed": False,
    "marketplace_download_performed": False,
    "model_candidate_created": False,
    "provider_runtime_allowed": False,
    "model_output_generated": False,
    "action_performed": False,
    "compliance_certification_emitted": False,
    "legal_advice_emitted": False,
    "audit_pass_claimed": False,
    "attestation_success_claimed": False,
    "truth_certification_emitted": False,
    "product_readiness_claimed": False,
    "product_release_performed": False,
    "final_answer_authority_granted": False,
    "accepted_evidence_authority_granted": False,
}

RECEIPT_CHAIN_EXPORT_NON_AUTHORITY_BOUNDARY = {
    "receipt_chain_export_is_not_external_export": True,
    "receipt_chain_export_is_not_truth_certification": True,
    "receipt_chain_export_is_not_source_truth_certification": True,
    "receipt_chain_export_is_not_memory_write_authorization": True,
    "receipt_chain_export_is_not_deployment_authority": True,
    "receipt_chain_export_is_not_compliance_certification": True,
    "receipt_chain_export_is_not_legal_advice": True,
    "receipt_chain_export_is_not_audit_pass": True,
    "receipt_chain_export_is_not_attestation_success": True,
    "receipt_chain_export_is_not_product_release": True,
    "receipt_chain_export_is_not_product_readiness": True,
    "receipt_chain_export_is_not_final_answer_authority": True,
    "receipt_chain_export_is_not_accepted_evidence_authority": True,
    "receipt_chain_export_does_not_call_provider": True,
    "receipt_chain_export_does_not_call_network": True,
    "receipt_chain_export_does_not_execute_tools": True,
    "receipt_chain_export_does_not_perform_actions": True,
    "receipt_chain_export_does_not_write_memory": True,
    "receipt_chain_export_does_not_admit_atlas_memory": True,
    "receipt_chain_export_does_not_export_traces": True,
    "receipt_chain_export_does_not_federate_pmr": True,
    "human_review_required": True,
}

RECEIPT_CHAIN_EXPORT_BLOCKED_CLAIMS = [
    "receipt chain export certifies truth",
    "receipt chain export certifies source truth",
    "receipt chain export authorizes memory write",
    "receipt chain export authorizes deployment",
    "receipt chain export certifies compliance",
    "receipt chain export provides legal advice",
    "receipt chain export passes audit",
    "receipt chain export releases product",
    "receipt chain export proves product readiness",
    "receipt chain export grants final-answer authority",
    "receipt chain export grants accepted-evidence authority",
    "receipt chain export performs external export",
    "receipt chain export calls provider",
    "receipt chain export calls network",
    "receipt chain export writes memory",
    "receipt chain export admits Atlas memory",
    "receipt chain export exports traces",
    "receipt chain export federates PMR",
    "receipt chain export executes tools",
    "receipt chain export performs actions",
    "chain hash proves truth",
    "chain hash proves compliance",
    "manifest row is accepted evidence",
    "local manifest is audit pass",
    "local manifest is product release",
]

RECEIPT_CHAIN_EXPORT_ALLOWED_CLAIM = (
    "AEGIS-RECEIPT-CHAIN-EXPORT-00 implements local deterministic AEGIS receipt-chain export manifests that assemble admission, source-scope, consent, grounding, instruction-quarantine, model-candidate gate, action-firewall, failure receipt, and non-authority-boundary artifacts into an ordered local manifest with SHA-256 hashes and references, while preserving that the manifest is evidence-support metadata only and does not perform external export, call providers, perform network calls, execute tools, perform actions, write memory, admit Atlas memory, export traces, federate PMR, certify compliance, provide legal advice, pass audits, claim product readiness, release product, certify truth, emit final answers, grant final-answer authority, or grant accepted-evidence authority."
)

AEGIS_LOCAL_RUNTIME_ENFORCEMENT_PHASE = "AEGIS-LOCAL-RUNTIME-ENFORCEMENT-ADAPTER-00"
LOCAL_RUNTIME_ENFORCEMENT_FAILURE_RECEIPT_NAME = "aegis_local_runtime_enforcement_failure_receipt.json"

LOCAL_RUNTIME_ENFORCEMENT_FALSE_FLAGS = {
    "operation_performed": False,
    "tool_execution_allowed": False,
    "tool_execution_performed": False,
    "action_allowed": False,
    "action_performed": False,
    "file_write_allowed": False,
    "file_write_performed": False,
    "file_delete_allowed": False,
    "file_delete_performed": False,
    "connector_pull_allowed": False,
    "connector_pull_performed": False,
    "connector_push_allowed": False,
    "connector_push_performed": False,
    "provider_runtime_allowed": False,
    "provider_runtime_performed": False,
    "network_call_allowed": False,
    "network_call_performed": False,
    "memory_write_allowed": False,
    "memory_write_performed": False,
    "atlas_memory_admission_allowed": False,
    "atlas_memory_admission_performed": False,
    "trace_export_allowed": False,
    "trace_export_performed": False,
    "pmr_federation_allowed": False,
    "pmr_federation_performed": False,
    "package_install_allowed": False,
    "package_install_performed": False,
    "package_activation_allowed": False,
    "package_activation_performed": False,
    "package_execution_allowed": False,
    "package_execution_performed": False,
    "payment_processing_allowed": False,
    "payment_processing_performed": False,
    "subscription_billing_allowed": False,
    "subscription_billing_performed": False,
    "marketplace_download_allowed": False,
    "marketplace_download_performed": False,
    "model_candidate_generation_allowed": False,
    "model_candidate_created": False,
    "model_output_generated": False,
    "final_answer_emit_allowed": False,
    "final_answer_authority_granted": False,
    "accepted_evidence_mark_allowed": False,
    "accepted_evidence_authority_granted": False,
    "compliance_certification_emitted": False,
    "legal_advice_emitted": False,
    "audit_pass_claimed": False,
    "truth_certification_emitted": False,
    "product_readiness_claimed": False,
    "product_release_performed": False,
}

LOCAL_RUNTIME_ENFORCEMENT_NON_AUTHORITY_BOUNDARY = {
    "local_runtime_enforcement_adapter_is_not_truth_certification": True,
    "local_runtime_enforcement_adapter_is_not_source_truth_certification": True,
    "local_runtime_enforcement_adapter_is_not_memory_write_authorization": True,
    "local_runtime_enforcement_adapter_is_not_deployment_authority": True,
    "local_runtime_enforcement_adapter_is_not_compliance_certification": True,
    "local_runtime_enforcement_adapter_is_not_legal_advice": True,
    "local_runtime_enforcement_adapter_is_not_audit_pass": True,
    "local_runtime_enforcement_adapter_is_not_attestation_success": True,
    "local_runtime_enforcement_adapter_is_not_product_release": True,
    "local_runtime_enforcement_adapter_is_not_product_readiness": True,
    "local_runtime_enforcement_adapter_is_not_final_answer_authority": True,
    "local_runtime_enforcement_adapter_is_not_accepted_evidence_authority": True,
    "local_runtime_enforcement_adapter_does_not_execute_tools": True,
    "local_runtime_enforcement_adapter_does_not_perform_actions": True,
    "local_runtime_enforcement_adapter_does_not_call_provider": True,
    "local_runtime_enforcement_adapter_does_not_call_network": True,
    "local_runtime_enforcement_adapter_does_not_write_files": True,
    "local_runtime_enforcement_adapter_does_not_delete_files": True,
    "local_runtime_enforcement_adapter_does_not_pull_connectors": True,
    "local_runtime_enforcement_adapter_does_not_push_connectors": True,
    "local_runtime_enforcement_adapter_does_not_write_memory": True,
    "local_runtime_enforcement_adapter_does_not_admit_atlas_memory": True,
    "local_runtime_enforcement_adapter_does_not_export_traces": True,
    "local_runtime_enforcement_adapter_does_not_federate_pmr": True,
    "local_runtime_enforcement_adapter_does_not_create_model_candidates": True,
    "local_runtime_enforcement_adapter_does_not_generate_model_output": True,
    "human_review_required": True,
}

LOCAL_RUNTIME_ENFORCEMENT_BLOCKED_CLAIMS = [
    "local runtime enforcement adapter certifies truth",
    "local runtime enforcement adapter authorizes memory write",
    "local runtime enforcement adapter authorizes deployment",
    "local runtime enforcement adapter certifies compliance",
    "local runtime enforcement adapter provides legal advice",
    "local runtime enforcement adapter passes audit",
    "local runtime enforcement adapter releases product",
    "local runtime enforcement adapter proves product readiness",
    "local runtime enforcement adapter grants final-answer authority",
    "local runtime enforcement adapter grants accepted-evidence authority",
    "local runtime enforcement adapter executes tools",
    "local runtime enforcement adapter performs actions",
    "local runtime enforcement adapter writes files",
    "local runtime enforcement adapter deletes files",
    "local runtime enforcement adapter pulls connector data",
    "local runtime enforcement adapter pushes connector data",
    "local runtime enforcement adapter calls provider",
    "local runtime enforcement adapter calls network",
    "local runtime enforcement adapter writes memory",
    "local runtime enforcement adapter admits Atlas memory",
    "local runtime enforcement adapter exports traces",
    "local runtime enforcement adapter federates PMR",
    "local runtime enforcement adapter creates model candidate",
    "local runtime enforcement adapter generates model output",
    "preflight allowed means operation performed",
    "preflight allowed means final answer authority",
    "completed-with-failures chain permits action execution",
    "receipt chain manifest executes runtime",
]

LOCAL_RUNTIME_ENFORCEMENT_ALLOWED_CLAIM = (
    "AEGIS-LOCAL-RUNTIME-ENFORCEMENT-ADAPTER-00 implements a local deterministic AEGIS preflight adapter that consumes receipt-chain export manifests and requested operation metadata to return fail-closed operation-eligibility decisions for local callers, while preserving that the adapter does not execute tools, perform actions, write or delete files, pull or push connectors, call providers, perform network calls, write memory, admit Atlas memory, export traces, federate PMR, install packages, activate packages, execute packages, process payments, bill subscriptions, download marketplace packages, create model candidates, generate model output, certify compliance, provide legal advice, pass audits, claim product readiness, release product, certify truth, emit final answers, grant final-answer authority, or grant accepted-evidence authority."
)

AEGIS_UI_PREFLIGHT_STATUS_SURFACE_PHASE = "AEGIS-UI-PREFLIGHT-STATUS-SURFACE-00"
UI_PREFLIGHT_STATUS_SURFACE_PACKET_NAME = "aegis_ui_preflight_status_surface_packet.json"
UI_PREFLIGHT_STATUS_SURFACE_MARKDOWN_NAME = "aegis_ui_preflight_status_surface.md"
UI_PREFLIGHT_STATUS_SURFACE_HTML_NAME = "aegis_ui_preflight_status_surface.html"
UI_PREFLIGHT_STATUS_SURFACE_FAILURE_RECEIPT_NAME = "aegis_ui_preflight_status_surface_failure_receipt.json"
UI_PREFLIGHT_STATUS_SURFACE_BOUNDARY_NAME = "aegis_ui_preflight_status_surface_non_authority_boundary.json"

UI_PREFLIGHT_STATUS_SURFACE_FALSE_FLAGS = {
    "source_packet_modified": False,
    "decision_recalculated_from_source_content": False,
    "authorization_inferred": False,
    "interactive_action_enabled": False,
    "operation_performed": False,
    "tool_execution_performed": False,
    "action_performed": False,
    "file_write_performed": False,
    "file_delete_performed": False,
    "connector_pull_performed": False,
    "connector_push_performed": False,
    "provider_runtime_performed": False,
    "network_call_performed": False,
    "memory_write_performed": False,
    "atlas_memory_admission_performed": False,
    "trace_export_performed": False,
    "pmr_federation_performed": False,
    "package_install_performed": False,
    "package_activation_performed": False,
    "package_execution_performed": False,
    "payment_processing_performed": False,
    "subscription_billing_performed": False,
    "marketplace_download_performed": False,
    "model_candidate_created": False,
    "model_output_generated": False,
    "final_answer_authority_granted": False,
    "accepted_evidence_authority_granted": False,
    "compliance_certification_emitted": False,
    "legal_advice_emitted": False,
    "audit_pass_claimed": False,
    "attestation_success_claimed": False,
    "truth_certification_emitted": False,
    "product_readiness_claimed": False,
    "product_release_performed": False,
    "raw_source_content_displayed": False,
    "raw_prompt_content_displayed": False,
    "secret_content_displayed": False,
    "color_only_status_used": False,
}

UI_PREFLIGHT_STATUS_SURFACE_NON_AUTHORITY_BOUNDARY = {
    "ui_preflight_status_surface_is_not_enforcement_authority": True,
    "ui_preflight_status_surface_is_not_action_authority": True,
    "ui_preflight_status_surface_is_not_truth_certification": True,
    "ui_preflight_status_surface_is_not_source_truth_certification": True,
    "ui_preflight_status_surface_is_not_memory_write_authorization": True,
    "ui_preflight_status_surface_is_not_deployment_authority": True,
    "ui_preflight_status_surface_is_not_compliance_certification": True,
    "ui_preflight_status_surface_is_not_legal_advice": True,
    "ui_preflight_status_surface_is_not_audit_pass": True,
    "ui_preflight_status_surface_is_not_attestation_success": True,
    "ui_preflight_status_surface_is_not_product_release": True,
    "ui_preflight_status_surface_is_not_product_readiness": True,
    "ui_preflight_status_surface_is_not_final_answer_authority": True,
    "ui_preflight_status_surface_is_not_accepted_evidence_authority": True,
    "ui_preflight_status_surface_does_not_execute_tools": True,
    "ui_preflight_status_surface_does_not_perform_actions": True,
    "ui_preflight_status_surface_does_not_call_provider": True,
    "ui_preflight_status_surface_does_not_call_network": True,
    "ui_preflight_status_surface_does_not_write_user_files": True,
    "ui_preflight_status_surface_does_not_delete_files": True,
    "ui_preflight_status_surface_does_not_pull_connectors": True,
    "ui_preflight_status_surface_does_not_push_connectors": True,
    "ui_preflight_status_surface_does_not_write_memory": True,
    "ui_preflight_status_surface_does_not_admit_atlas_memory": True,
    "ui_preflight_status_surface_does_not_export_traces": True,
    "ui_preflight_status_surface_does_not_federate_pmr": True,
    "ui_preflight_status_surface_does_not_create_model_candidates": True,
    "ui_preflight_status_surface_does_not_generate_model_output": True,
    "human_review_required": True,
}

UI_PREFLIGHT_STATUS_SURFACE_BLOCKED_CLAIMS = [
    "UI preflight status surface certifies truth",
    "UI preflight status surface authorizes memory write",
    "UI preflight status surface authorizes deployment",
    "UI preflight status surface certifies compliance",
    "UI preflight status surface provides legal advice",
    "UI preflight status surface passes audit",
    "UI preflight status surface releases product",
    "UI preflight status surface proves product readiness",
    "UI preflight status surface grants final-answer authority",
    "UI preflight status surface grants accepted-evidence authority",
    "UI preflight status surface executes tools",
    "UI preflight status surface performs actions",
    "UI preflight status surface calls provider",
    "UI preflight status surface calls network",
    "UI preflight status surface writes user files",
    "UI preflight status surface writes memory",
    "UI preflight status surface creates model candidates",
    "UI preflight status surface generates model output",
    "ready for preview means operation performed",
    "ready with controls means action authorized",
    "review required means audit failed",
    "blocked means illegal",
    "elevated review required means compliance breach",
    "green status proves safety",
    "surface hash certifies truth",
    "failure receipt proves audit failure",
    "status surface can override AEGIS preflight",
]

UI_PREFLIGHT_STATUS_SURFACE_ALLOWED_CLAIM = (
    "AEGIS-UI-PREFLIGHT-STATUS-SURFACE-00 implements a local deterministic and accessible presentation surface that consumes AEGIS local-runtime preflight packets and renders fail-closed JSON, Markdown, and static HTML status artifacts for preview, review, blocked, and elevated-review outcomes, while preserving that the surface does not alter the source decision, infer authorization, execute tools, perform actions, write user files, call providers, perform network calls, write memory, create model candidates, generate model output, certify compliance, provide legal advice, pass audits, claim product readiness, release product, certify truth, emit final answers, grant final-answer authority, or grant accepted-evidence authority."
)
